### ISSUE TITLE
Break in the wavelength solution over the slit

### ISSUE THREAD

**Issue by jsbridge** [Keck-DataReductionPipelines/MosfireDRP#122]
I have a question about what is going on with the application of the wavelength solution step.  I have a sparse mask (only three objects) and for two fairly long slits, the wavelength solution jumps about about halfway down. Any idea why this would happen? I've attached a couple of files. The file output from Wavelength.fit_lambda_interactively() looks fine. 
[rectified_wave_stack_Y_m180521_0048-0133.fits.gz](https://github.com/Keck-DataReductionPipelines/MosfireDRP/files/2081236/rectified_wave_stack_Y_m180521_0048-0133.fits.gz)
[lambda_solution_wave_stack_Y_m180521_0048-0133.fits.zip](https://github.com/Keck-DataReductionPipelines/MosfireDRP/files/2081237/lambda_solution_wave_stack_Y_m180521_0048-0133.fits.zip)

**Comment by jsbridge** [comment]
Just checking in again to see if anyone has any ideas about this?

**Comment by MosfireDRP** [comment]
I am afraid not. 
We tried everything that we could think of to make the pipeline more robust when using long slits
We are looking at the possibility of changing the entire structure of the Wavelength module but that is going to take a while.

If you have long slits and only a single object in your slits, you might want to look at if your object is calibrated correctly or not. If your target is the good part of the slit, then you don’t need to worry about the wavelength jumps. You can check that by looking at the wavelength of known features, or at sky lines.

I am afraid we need to file this away as a bug of the pipeline.
If you feel that you can contribute to the effort, the code is open and we appreciate any insight you might have on making it more stable.

Luca

**Comment by lucarizzi** [comment]
Not sure if you are still working on these data, but we think we found a solution to the problem by extending the range of the search for the wavelength cross-correlation. Please git pull the latest version of the pipeline. I tried it on your data and I don't see a wavelength break anymore.
