### ISSUE TITLE
problem with mospy handle

### ISSUE THREAD

**Issue by sinataamoli** [Keck-DataReductionPipelines/MosfireDRP#149]
Hi all,

I'm new to use MOSFIRE DRP and I followed the steps in [https://keck-datareductionpipelines.github.io/MosfireDRP/] to install the DRP. I'm not sure if it's installed correctly as I cannot use mospy handle

- I've created the env using: `conda create --no-default-packages -c astropy -n mospy python=3.6.3 astropy=2.0.3 ccdproc=1.3.0 ipython=6.2.1 numpy=1.13.3 scipy=1.0.0 PyQt=5.6.0` (successfully done)
- activated the created env
- I installed astropy-helpers-4.0.1
- setup completed without any error 
Installation manual states that an executable `mospy` file should be at this path: (~/anaconda/envs/mospy/bin/mospy) but I have these files:  mospy (it's a C shell script. is it the file that instruction mentions?), mospy_db.py, mospy_handle, mospy_what.py
When I use the command `mospy handle /home/[path to data]/DRP_Test_Case_Hband/2012sep10/*.fits` I get this error `bash: /home/.../anaconda3/envs/mospy/bin/mospy: /bin/csh: bad interpreter: No such file or directory`

does anyone know the problem?

**Comment by joshwalawender** [comment]
Hi @sinataamoli can you try the following test for me:

Activate the relevant environment:
`conda activate mospy`

then invoke mospy
`mospy`

That should give you a standard python interpreter.  Does that work on your system?

-Josh

**Comment by sinataamoli** [comment]
> Hi @sinataamoli can you try the following test for me:
> 
> Activate the relevant environment:
> `conda activate mospy`
> 
> then invoke mospy
> `mospy`
> 
> That should give you a standard python interpreter. Does that work on your system?
> 
> -Josh

Thanks for the answer. This is exactly what I did, but still doesn't work. This is what happens:
`(base) [sina@sina reduced]$ conda activate mospy`
`(mospy) [sina@sina reduced]$ mospy handle /home/sina/anaconda3/DATA/2012sep10/*.fits`
`bash: /home/sina/anaconda3/envs/mospy/bin/mospy: /bin/csh: bad interpreter: No such file or directory`

**Comment by joshwalawender** [comment]
Can you just invoke `mospy`, not `mospy handle`?

**Comment by sinataamoli** [comment]
I tried `mospy` instead of `mospy handle` in terminal and I got the error again:
`(mospy) [sina@sina reduced]$ mospy /home/sina/anaconda3/DATA/2012sep10/*.fits`
`bash: /home/sina/anaconda3/envs/mospy/bin/mospy: /bin/csh: bad interpreter: No such file or directory`
I'm not sure if I'm doing anything wrong. I'm using Manjaro and mospy was installed without any error.


> Can you just invoke `mospy`, not `mospy handle`?

I tried `mospy` instead of `mospy handle` in terminal and I got the error again:
`(mospy) [sina@sina reduced]$ mospy /home/sina/anaconda3/DATA/2012sep10/*.fits`
`bash: /home/sina/anaconda3/envs/mospy/bin/mospy: /bin/csh: bad interpreter: No such file or directory`
I'm not sure if I'm doing anything wrong. I'm using Manjaro and mospy was installed without any error.

**Comment by followthesheep** [comment]
Are you using linux? It sounds like you might need to install cshell. I think the script uses csh to run itself.

**Comment by sinataamoli** [comment]
> Are you using linux? It sounds like you might need to install cshell. I think the script uses csh to run itself.

Yes, that was the problem. it worked. Thanks a lot
