### ISSUE TITLE
Making installation easier - python packaging

### ISSUE THREAD

**Issue by followthesheep** [Keck-DataReductionPipelines/MosfireDRP#18]
Hi everyone,
I started a new branch of the pipeline called install_update in order to make the MOSFIRE DRP a normal python package. I'm hoping this will make the installation smoother and makes it easier to develop on. 

The main advantage of the new packaging is:
- installs like normal python packages (python setup.py install)
- does not rely on environment variables. It will install itself into the current python environment, so it works well with Ureka. It will also work well for people who use custom python environments, or people like us who want to test this in isolation. 
- a testing framework is built into the package (if we decide in the future to write tests)
- future documentation can be put in readthedocs.org as in many other python packages.

The new proposed installation procedure is as follows:

git clone git@github.com:Mosfire-DataReductionPipeline/MosfireDRP.git mosfire

If using Ureka:

    ur_setup

Then: 

    cd mosfire

    python setup.py install

or, if developing the code (just make symbolic links in python environment, so you can edit in current directory)

    python setup.py develop

After this installs, you should be able to run the data reduction pipeline as normal, except you can skip the step of setting up the MOSPATH and PYTHONPATH environment variables. 

The implementation as I've put in right now can be installed in the normal old way as well. 

In order to get this to work, I've copied a few things around. The MOSFIRE directory now has a 'data' directory to conform with the python packages for the location of data. I've copied the bad pixel mask and the platescale file there. I've also modified the pipeline so that it knows about the relative path instead of relying on the environment variable. In the future, we can remove the redundant files, but I wanted some backward compatibility for now. 

I realize this is a big change to the installation of the pipeline, but I have found that it makes developing on it much faster. 

I've put this version of the code on a separate branch called install_update. If you would like to test it, just checkout that branch with:

    git checkout install_update

after you clone the MOSFIRE DRP from git. 

Let me know what you think!

Tuan

**Comment by lucarizzi** [comment]
Done
