### ISSUE TITLE
Compatibility with numpy 1.9 and related issues

### ISSUE THREAD

**Issue by athoag** [Keck-DataReductionPipelines/MosfireDRP#20]
Hi, this is my first attempt to reduce MOSFIRE data using the pipeline now available on GitHub (downloaded today 4/30/2015). I have been able to successfully reduce data previously using and older release of the DRP, which I downloaded in December 2013.

I am currently running OS X 10.9.5 with Ureka python 1.5.1. I also see the issue see on OS X 10.9.2  (laptop) with the same version of Ureka installed.

I am following through the documentation (https://mosfire-datareductionpipeline.github.io/MosfireDRP/MOSFIRE_DRP_Manual.docx) available for the current DRP release, and I see expected behavior up to the interactive wavelength fitting step described on pages 10-13 of the documentation.

The issue arises when I run the following line in the driver file that I have been editing: 
Wavelength.fit_lambda_interactively(maskname, band, obsfiles,waveops)

I get what looks like a healthy initialization of this funciton, where the offset files are loaded:

Loading: Offset_1.25.txt
Loading: Offset_-1.25.txt

and then a list of files contained in the offset files is printed (I will not show them for brevity), followed by the lines:

Started interactive solution
Extracting at 1990 
Launching graphics display.    
Waiting

The python figure pops up and I see a spectrum in the correct band with a bunch of easily recognizable sky lines and red vertical lines. All of the key options that appear upon pressing the "h" key appear to work normally except for the fitting buttons, which are listed as "f" and "/". In the documentation (https://mosfire-datareductionpipeline.github.io/MosfireDRP/MOSFIRE_DRP_Manual.docx) under "MAJOR BUGFIXES" on page 1, it appears that "/" is now the preferred key to fit the spectrum, whereas "f" was preferred in the previous release I was using.

When I press "/" only the x,y pair at the cursor location is returned and no fit is performed; I do not see any points appear in the bottom subfigure, which remains blank white. Pressing "f" also prints the x,y pair, but also returns the following long traceback, ultimately leading to a ValueError in one of numpy's core modules:

f 9792.98764132 62.8975535168
Fitting
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/Austin/progs/Ureka/python/lib/python2.7/lib-tk/Tkinter.py", line 1470, in __call__
    return self.func(*args)
  File "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 484, in key_press
    FigureCanvasBase.key_press_event(self, key, guiEvent=event)
  File "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/backend_bases.py", line 1816, in key_press_event
    self.callbacks.process(s, event)
  File "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/cbook.py", line 540, in process
    proxy(*args, **kwargs)
  File "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/cbook.py", line 415, in __call__
    return mtd(*args, **kwargs)
  File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Wavelength.py", line 1930, in __call__
    actions_mouseless[kp](x, y)
  File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Wavelength.py", line 1879, in fit_event
    self.spec, self.options)
  File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Wavelength.py", line 1454, in find_known_lines
    error=istd)
  File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Fit.py", line 153, in mpfitpeak
    return mpfit.mpfit(gaussian_residuals, parinfo=parinfo, functkw=fa, quiet=1)
  File "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/stsci.tools-3.2.2-py2.7.egg/stsci/tools/nmpfit.py", line 1158, in __init__
    delta, wa1, wa2, par=par)
  File "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/stsci.tools-3.2.2-py2.7.egg/stsci/tools/nmpfit.py", line 2088, in lmpar
    [r, x, sdiag] = self.qrsolv(r, ipvt, wa1, qtb, sdiag)
  File "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/stsci.tools-3.2.2-py2.7.egg/stsci/tools/nmpfit.py", line 1915, in qrsolv
    numpy.put(x, ipvt, wa)
  File "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 444, in put
    return a.put(ind, v, mode)
ValueError: put: output array is read-only

I have been able to get around this by altering my "fromnumeric.py" function, turning the error-causing line:

return a.put(ind,v,mode)

into a try, except ValueError pair. However, I do not like this as a permanent solution as it involves changing a function external to the DRP, particularly one that I use a lot elsewhere. And while the fitting after this "fix" appears to work, I get a slew of warnings and the next step in the Driver file fails anyway.

Sincerely,
Austin Hoag

**Comment by csteidel** [comment]
Hi Austin,
    This sounds like it must have to do with some recent change to Ureka python 
(I am running v 1.4 and everything works fine with the “f” key). However, until
someone who knows python better than I do looks at it, I suggest adding
“bypass=True” to your call of Wavelength.fit_lambda_interactively (see below), a 
relatively new feature in the DRP that (in my experience, entirely successfully) 
does the initial fit automatically without user interaction.  Example line in driver script:

   Wavelength.fit_lambda_interactively(maskname, band, obsfiles,waveops, bypass=True)

Hope that helps, at least for the time being. 

      -Chuck

**Comment by lucarizzi** [comment]
Dear Austin
I am currently on vacation but I will be able to help you soon. 
Quick question: did you download the official released version which is linked from the misfire webpage we host at keck, or did you clone the development version directly from github ? 
In this second case, may I advise that you try again with the official release ?

Thank you 
Luca Rizzi

**Comment by athoag** [comment]
Hi Chuck,

Thank you for getting back to me quickly. Regarding the bypass option, I
tried running the same fit_lambda_interactively() command as I wrote
before, but with bypass=True and got the same error message back. In light
of your comment about the Ureka version, I still have version 1.0 on my
machine, so I will try with that version enabled.

Thanks,
Austin

On Thu, Apr 30, 2015 at 3:46 PM, csteidel <notifications@github.com> wrote:

> Hi Austin,
> This sounds like it must have to do with some recent change to Ureka
> python
> (I am running v 1.4 and everything works fine with the “f” key). However,
> until
> someone who knows python better than I do looks at it, I suggest adding
> “bypass=True” to your call of Wavelength.fit_lambda_interactively (see
> below), a
> relatively new feature in the DRP that (in my experience, entirely
> successfully)
> does the initial fit automatically without user interaction. Example line
> in driver script:
>
> Wavelength.fit_lambda_interactively(maskname, band, obsfiles,waveops,
> bypass=True)
>
> Hope that helps, at least for the time being.
>
> -Chuck
>
>
> > On Apr 30, 2015, at 3:05 PM, Austin Hoag <notifications@github.com>
> wrote:
> >
> > Hi, this is my first attempt to reduce MOSFIRE data using the pipeline
> now available on GitHub (downloaded today 4/30/2015). I have been able to
> successfully reduce data previously using and older release of the DRP,
> which I downloaded in December 2013.
> >
> > I am currently running OS X 10.9.5 with Ureka python 1.5.1. I also see
> the issue see on OS X 10.9.2 (laptop) with the same version of Ureka
> installed.
> >
> > I am following through the documentation (
> https://mosfire-datareductionpipeline.github.io/MosfireDRP/MOSFIRE_DRP_Manual.docx
> <
> https://mosfire-datareductionpipeline.github.io/MosfireDRP/MOSFIRE_DRP_Manual.docx>)
> available for the current DRP release, and I see expected behavior up to
> the interactive wavelength fitting step described on pages 10-13 of the
> documentation.
> >
> > The issue arises when I run the following line in the driver file that I
> have been editing:
> > Wavelength.fit_lambda_interactively(maskname, band, obsfiles,waveops)
> >
> > I get what looks like a healthy initialization of this funciton, where
> the offset files are loaded:
> >
> > Loading: Offset_1.25.txt
> > Loading: Offset_-1.25.txt
> >
> > and then a list of files contained in the offset files is printed (I
> will not show them for brevity), followed by the lines:
> >
> > Started interactive solution
> > Extracting at 1990
> > Launching graphics display.
> >
> > Waiting
> >
> > The python figure pops up and I see a spectrum in the correct band with
> a bunch of easily recognizable sky lines and red vertical lines. All of the
> key options that appear upon pressing the "h" key appear to work normally
> except for the fitting buttons, which are listed as "f" and "/". In the
> documentation (
> https://mosfire-datareductionpipeline.github.io/MosfireDRP/MOSFIRE_DRP_Manual.docx
> <
> https://mosfire-datareductionpipeline.github.io/MosfireDRP/MOSFIRE_DRP_Manual.docx>)
> under "MAJOR BUGFIXES" on page 1, it appears that "/" is now the preferred
> key to fit the spectrum, whereas "f" was preferred in the previous release
> I was using.
> >
> > When I press "/" only the x,y pair at the cursor location is returned
> and no fit is performed; I do not see any points appear in the bottom
> subfigure, which remains blank white. Pressing "f" also prints the x,y
> pair, but also returns the following long traceback, ultimately leading to
> a ValueError in one of numpy's core modules:
> >
> > f 9792.98764132 62.8975535168
> > Fitting
> > Exception in Tkinter callback
> > Traceback (most recent call last):
> > File "/Users/Austin/progs/Ureka/python/lib/python2.7/lib-tk/Tkinter.py",
> line 1470, in call
> > return self.func(args)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/backends/backend_tkagg.py",
> line 484, in key_press
> > FigureCanvasBase.key_press_event(self, key, guiEvent=event)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/backend_bases.py",
> line 1816, in key_press_event
> > self.callbacks.process(s, event)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/cbook.py",
> line 540, in process
> > proxy(args, *kwargs)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/cbook.py",
> line 415, in call
> > return mtd(args, **kwargs)
> > File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Wavelength.py", line 1930,
> in call
> > actions_mouselesskp <x-msg://14/x,%20y>
> > File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Wavelength.py", line 1879,
> in fit_event
> > self.spec, self.options)
> > File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Wavelength.py", line 1454,
> in find_known_lines
> > error=istd)
> > File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Fit.py", line 153, in
> mpfitpeak
> > return mpfit.mpfit(gaussian_residuals, parinfo=parinfo, functkw=fa,
> quiet=1)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/stsci.tools-3.2.2-py2.7.egg/stsci/tools/nmpfit.py",
> line 1158, in init
> > delta, wa1, wa2, par=par)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/stsci.tools-3.2.2-py2.7.egg/stsci/tools/nmpfit.py",
> line 2088, in lmpar
> > [r, x, sdiag] = self.qrsolv(r, ipvt, wa1, qtb, sdiag)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/stsci.tools-3.2.2-py2.7.egg/stsci/tools/nmpfit.py",
> line 1915, in qrsolv
> > numpy.put(x, ipvt, wa)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/numpy/core/fromnumeric.py",
> line 444, in put
> > return a.put(ind, v, mode)
> > ValueError: put: output array is read-only
> >
> > I have been able to get around this by altering my "fromnumeric.py"
> function, turning the error-causing line:
> >
> > return a.put(ind,v,mode)
> >
> > into a try, except ValueError pair. However, I do not like this as a
> permanent solution as it involves changing a function external to the DRP,
> particularly one that I use a lot elsewhere. And while the fitting after
> this "fix" appears to work, I get a slew of warnings and the next step in
> the Driver file fails anyway.
> >
> > Sincerely,
> > Austin Hoag
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/Mosfire-DataReductionPipeline/MosfireDRP/issues/20>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mosfire-DataReductionPipeline/MosfireDRP/issues/20#issuecomment-97992185>
> .
>



-- 
Austin Hoag
Ph.D. Student
Department of Physics
University of California, Davis

**Comment by athoag** [comment]
Hi Luca,

I downloaded the DRP as a tar ball from here:
https://mosfire-datareductionpipeline.github.io/MosfireDRP/

I did not clone the GitHub repository.

Thanks,
Austin

On Thu, Apr 30, 2015 at 3:48 PM, lucarizzi <notifications@github.com> wrote:

> Dear Austin
> I am currently on vacation but I will be able to help you soon.
> Quick question: did you download the official released version which is
> linked from the misfire webpage we host at keck, or did you clone the
> development version directly from github ?
> In this second case, may I advise that you try again with the official
> release ?
>
> Thank you
> Luca Rizzi
>
>
> > On Apr 30, 2015, at 12:04 PM, Austin Hoag <notifications@github.com>
> wrote:
> >
> > Hi, this is my first attempt to reduce MOSFIRE data using the pipeline
> now available on GitHub (downloaded today 4/30/2015). I have been able to
> successfully reduce data previously using and older release of the DRP,
> which I downloaded in December 2013.
> >
> > I am currently running OS X 10.9.5 with Ureka python 1.5.1. I also see
> the issue see on OS X 10.9.2 (laptop) with the same version of Ureka
> installed.
> >
> > I am following through the documentation (
> https://mosfire-datareductionpipeline.github.io/MosfireDRP/MOSFIRE_DRP_Manual.docx)
> available for the current DRP release, and I see expected behavior up to
> the interactive wavelength fitting step described on pages 10-13 of the
> documentation.
> >
> > The issue arises when I run the following line in the driver file that I
> have been editing:
> > Wavelength.fit_lambda_interactively(maskname, band, obsfiles,waveops)
> >
> > I get what looks like a healthy initialization of this funciton, where
> the offset files are loaded:
> >
> > Loading: Offset_1.25.txt
> > Loading: Offset_-1.25.txt
> >
> > and then a list of files contained in the offset files is printed (I
> will not show them for brevity), followed by the lines:
> >
> > Started interactive solution
> > Extracting at 1990
> > Launching graphics display.
> >
> > Waiting
> >
> > The python figure pops up and I see a spectrum in the correct band with
> a bunch of easily recognizable sky lines and red vertical lines. All of the
> key options that appear upon pressing the "h" key appear to work normally
> except for the fitting buttons, which are listed as "f" and "/". In the
> documentation (
> https://mosfire-datareductionpipeline.github.io/MosfireDRP/MOSFIRE_DRP_Manual.docx)
> under "MAJOR BUGFIXES" on page 1, it appears that "/" is now the preferred
> key to fit the spectrum, whereas "f" was preferred in the previous release
> I was using.
> >
> > When I press "/" only the x,y pair at the cursor location is returned
> and no fit is performed; I do not see any points appear in the bottom
> subfigure, which remains blank white. Pressing "f" also prints the x,y
> pair, but also returns the following long traceback, ultimately leading to
> a ValueError in one of numpy's core modules:
> >
> > f 9792.98764132 62.8975535168
> > Fitting
> > Exception in Tkinter callback
> > Traceback (most recent call last):
> > File "/Users/Austin/progs/Ureka/python/lib/python2.7/lib-tk/Tkinter.py",
> line 1470, in call
> > return self.func(args)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/backends/backend_tkagg.py",
> line 484, in key_press
> > FigureCanvasBase.key_press_event(self, key, guiEvent=event)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/backend_bases.py",
> line 1816, in key_press_event
> > self.callbacks.process(s, event)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/cbook.py",
> line 540, in process
> > proxy(args, *kwargs)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/matplotlib-1.4.2-py2.7-macosx-10.6-x86_64.egg/matplotlib/cbook.py",
> line 415, in call
> > return mtd(args, **kwargs)
> > File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Wavelength.py", line 1930,
> in call
> > actions_mouselesskp
> > File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Wavelength.py", line 1879,
> in fit_event
> > self.spec, self.options)
> > File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Wavelength.py", line 1454,
> in find_known_lines
> > error=istd)
> > File "/Users/Austin/MOSFIRE/DRP_CODE/MOSFIRE/Fit.py", line 153, in
> mpfitpeak
> > return mpfit.mpfit(gaussian_residuals, parinfo=parinfo, functkw=fa,
> quiet=1)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/stsci.tools-3.2.2-py2.7.egg/stsci/tools/nmpfit.py",
> line 1158, in init
> > delta, wa1, wa2, par=par)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/stsci.tools-3.2.2-py2.7.egg/stsci/tools/nmpfit.py",
> line 2088, in lmpar
> > [r, x, sdiag] = self.qrsolv(r, ipvt, wa1, qtb, sdiag)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/stsci.tools-3.2.2-py2.7.egg/stsci/tools/nmpfit.py",
> line 1915, in qrsolv
> > numpy.put(x, ipvt, wa)
> > File
> "/Users/Austin/progs/Ureka/python/lib/python2.7/site-packages/numpy/core/fromnumeric.py",
> line 444, in put
> > return a.put(ind, v, mode)
> > ValueError: put: output array is read-only
> >
> > I have been able to get around this by altering my "fromnumeric.py"
> function, turning the error-causing line:
> >
> > return a.put(ind,v,mode)
> >
> > into a try, except ValueError pair. However, I do not like this as a
> permanent solution as it involves changing a function external to the DRP,
> particularly one that I use a lot elsewhere. And while the fitting after
> this "fix" appears to work, I get a slew of warnings and the next step in
> the Driver file fails anyway.
> >
> > Sincerely,
> > Austin Hoag
> >
> > —
> > Reply to this email directly or view it on GitHub.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mosfire-DataReductionPipeline/MosfireDRP/issues/20#issuecomment-97992382>
> .
>



-- 
Austin Hoag
Ph.D. Student
Department of Physics
University of California, Davis

**Comment by athoag** [comment]
Reverting back to Ureka v1.0 solved the issue.

**Comment by marusa** [comment]
Ciao guys,
Ok, this was a tedious one. I tried to downgrade to Ureka 1.4.1 using Yosemite
-You need to modify the install file so Yosemite is recognized, still it gives warning Warning: unknown OS type Darwin.14.3.0
-Ipython has a bug, up,down arrows do not work properly. Solution:
pip uninstall  ipython
pip install readline ipython

-from matplotlib import ft2font does not work:Library not loaded: /Users/Shared/ureka.iraf/ur_work/Ureka_osx-6_64_1.4.1/python/lib/libfreetype.6.dylib

    setenv DYLD_FALLBACK_LIBRARY_PATH /opt/X11/lib/:/usr/lib:/opt/local/lib/:/Users/marusa/progs/Ureka_1.4.1/Ureka/python/lib/
    
    -Tkinter is not installed. Argh. Do I really want to do this? And this is where it got ugly. Copied python executable from Ureka 1.5.1 and voila! Needless to say this kind of fixes are not recommended, and they took me a good portion of observing night to fix.


    Now I'm not sure why there is an issue, as the routine nmpfit.py is the same in both versions of ureka. But I have a feeling it is the numpy that is problematic, as it is complaining about numpy.put.
   Marusa

**Comment by lucarizzi** [comment]
I will start to collect here the necessary steps to fix this problem
It is to be noted that this is not connected to any change in the pipeline. Fit.py calls stsdas.tools. The version of stsdas.tools has not changed between Ureka 1.4.1 and 1.5.1: it is 3.2.2.
Fit.py calls nmpfit.py from stsdas.tools which in turns calls the diagonal method of numpy.
This has changed: in numpy 1.8 it used to return a writable array, in 1.9 it returns a read-only array.

Clearly this not a workaround but for the moment, I got nmpfit.py to work by modifying it around lines 1855

it used to say:

x=numpy.diagonal(r)

I changed it to:

x_copy = numpy.diagonal(r)
x=x_copy.copy()

thus creating a writable array that can then be modified by calling numpy.put method.

A horrible hack. I report it here just for the record. I will continue to investigate.

**Comment by MosfireDRP** [comment]
After modifying the stsdas.tools package, the resulting fit produced by the new numpy 1.9.1 is very different from the fit produced by the old one.

**Comment by MosfireDRP** [comment]
To close this ticket:

1. I have written an email to user support at STSCI, presented the problem, and asked them about their plans to fix nmpfit, as currently it does not work with numpy 1.9. This is a problem of stsci.tools vs. numpy, not a problem of the pipeline.

2. I will add comments to the manual specifying that ureka 1.4.1 is the last version that works with the pipeline. For users who want to use 1.5.1, they will also need to manually downgrade numpy to 1.8

3. We should look into the possibility of reducing our dependency from stsci packages. In this case, we are doing a rather simple lsq fit of the lines peaks to the observed spectrum. Maybe we should look into something simpler than nmpfit from stsci. Wouldn't optimize.lsqf do something similar?
Maybe this is a problem that could be tackled when have more resources unless somebody in the group feels like looking into it.

**Comment by MosfireDRP** [comment]
Comment added by Tuan Do:

There is a problem when using nmpfit from numpy 1.9 when the routine goes through the interactive wavelength fit. The error is as follows:

/group/ureka/Ureka/variants/common/lib/python2.7/site-packages/numpy/core/fromnumeric.pyc in put(a, ind, v, mode)
    442 
    443     """
--> 444     return a.put(ind, v, mode)
    445 
    446 

ValueError: put: output array is read-only
This can be traced to nmpfit.py:

   1919         ## Permute the components of z back to components of x
-> 1920         numpy.put(x, ipvt, wa)
   1921         return(r, x, sdiag)
I've copied nmpfit.py to nmpfit_mos.py and edited so this bug no longer happens. However, this means that MOSFIRE will need to use a different version of nmpfit for now until stsci fixes theirs.

I've fixed this in my branch 'install_update'. This is the repackaging branch. I had to do it in this branch because it was the only way for me to test it in my python environment. However, you can apply the fix to the main branch by just copying over three files from my branch:

Fit.py
nmpfit_mos.py
numerixenv.py

into the MOSFIRE directory

From:
https://github.com/Keck-DataReductionPipelines/MosfireDRP/tree/install_update/MOSFIRE

I've tested it and the interactive wavelength fitting seems to run. I haven't gone through the entire interactive fitting process though. The bypass=True mode does run completely.

**Comment by lucarizzi** [comment]
Tuan has fixed this problem using a local copy of the offending packages. 
Hopefully this will be solved in the future.
