### ISSUE TITLE
A data set for pipeline testing

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/MosfireDRP#21]
We would like to create a data set for pipeline testing, that encompasses all the reasonable observing modes, and possibly include some of the difficult cases that we are aware of. Tuan, Marc and Luca will contribute some data. Chuck and Nick already have a data set that they have been using to test. Any suggestion for the best way to collect this data in a single location?

**Comment by joshwalawender** [comment]
Just wanted to give a +1 to this idea as it would be very helpful for testing the upcoming 2016 release (e.g. PR #56 and an upcoming PR I'm working on for spectral extraction).  We could probably host a zip or tar.gz file somewhere on a Keck server and leave instructions for the user to pull it down using something like wget.

We have the "test case" zip file, but that does not cover a large sample of possible data which would need to be analyzed.  Some cases that need to be covered would include:
* a slitmask
* other common slit configurations such as long2pos, longslit, etc.
* each of the above in J, H, and K spectra
* preferably with a mix of bright continuum sources, faint continuum sources, and emission line sources

**Comment by joshwalawender** [comment]
Now have data set at Keck for more complete testing before releasing a new version of the DRP.
