### ISSUE TITLE
Automatic generation of the Driver file

### ISSUE THREAD

**Issue by MosfireDRP** [Keck-DataReductionPipelines/MosfireDRP#24]
I have started working on scripts to automatically generate the driver files.
I think I have it down for the case of a regular slitmask using sky lines.
I am attaching the file here.

I will work on extending it to more general cases, including longslit and long2pos.

We need to decide a little bit of logic. For example: if either or both the Ar.txt and Ne.txt are populated, do we want to assume that the observer wants to combine sky lines and arcs? or do we want to produce a default sky-only driver with the arcs addition commented out?

Anyhow, please feel free to try to run this file on your masks.

It is run by using mospy AutoDriver.py in the directory that contains your Offset_*.txt files

I am not importing it into github as yes, as it is very very preliminary.

import MOSFIRE
from MOSFIRE import IO, Wavelength
import os, glob
import pyfits as pf

class Driver:

    def __init__(self,outputFile,type):
        self.outputFile = outputFile
        self.type = type
        self.offsetFiles = []
        allowedTypes = ['slitmask', 'longslit', 'long2pos', 'long2pos_specphot']
        if self.type not in allowedTypes:
            print "Unknown driver type"
        else:
            print "Generating automatic driver file "+outputFile
            self.target = open(outputFile,'w')
            self.import_section()

    def addLine(self, line):
        self.target.write(line+"\n")

    def import_section(self):
        self.addLine("import os, time")
        self.addLine("import MOSFIRE")
        self.addLine("from MOSFIRE import Background, Combine, Detector, Flats, IO, Options, Rectify, Wavelength")
        self.addLine("import numpy as np, pylab as pl, pyfits as pf")
        self.addLine("np.seterr(all='ignore')")

    def addOffsetFile(self,offsetFile, resetList=False):
        if resetList:
            self.offsetFiles = []
        self.offsetFiles.append(offsetFile)

    def printObsfiles(self):
        self.addLine("obsfiles = "+str(self.offsetFiles))

    def printMaskAndBand(self):
        offsetfile = self.offsetFiles[0]
        fname = IO.list_file_to_strings(offsetfile)

        if os.path.isabs(fname[0]): path = fname[0]
        else: path = os.path.join(fname_to_path(fname[0]), fname[0])
        hdulist = pf.open(path)
        header = hdulist[0].header

        self.maskName = header['maskname']
        self.band = header['filter']
        self.addLine("maskname = '"+str(self.maskName)+"'")
        self.addLine("band = '"+str(self.band)+"'")

    def isEmpty(self,file):
        fname = IO.list_file_to_strings(file)
        if len(fname):
            return False
        else:
            return True

    def printFlat(self):

        # using only Flat.txt
        if os.path.isfile('Flat.txt'):
            if self.isEmpty('Flat.txt') is True:
                self.addLine("### WARNING: Flat.txt is empty! ###")
            flatLine = "Flats.handle_flats('Flat.txt', maskname, band, flatops)"

        # using both Flat.txt and FlatThermal.txt
        if os.path.isfile('FlatThermal.txt') and self.band is 'K':
            if self.isEmpty('FlatThermal.txt') is True:
                self.addLine("### WARNING: FlatThermal.txt is empty! ###")
            flatLine = "Flats.handle_flats('Flat.txt', maskname, band, flatops,lampOffList='FlatThermal.txt')"

        # write the resulting line
        self.addLine(flatLine)

    def printWavelengthFit(self):
        # regular mask, with sky lines
        self.addLine("Wavelength.imcombine(obsfiles, maskname, band, waveops)")
        self.addLine("Wavelength.fit_lambda_interactively(maskname, band, obsfiles,waveops)")
        self.addLine("Wavelength.fit_lambda(maskname, band, obsfiles, obsfiles,waveops)")
        self.addLine("Wavelength.apply_lambda_simple(maskname, band, obsfiles, waveops)")
        # determine waveleng name
        files = IO.list_file_to_strings(self.offsetFiles)
        self.waveName = "lambda_solution_"+str(Wavelength.filelist_to_wavename(files, self.band, self.maskName,""))
        #self.addLine(self.waveName)

    def printBackground(self):
        self.addLine("Background.handle_background(obsfiles,'"+str(self.waveName)+"',maskname,band,waveops)")

    def printRectification(self):
        self.addLine('redfiles = ["eps_" + file + ".fits" for file in obsfiles]')
        self.addLine('Rectify.handle_rectification(maskname, redfiles,"'+str(self.waveName)+'",band,obsfiles,waveops)')
        
    def CloseFile(self):
        self.target.close()

def OffsetPairs():

    offsetFiles = glob.glob("Offset_*.txt")
    offsets = [abs(float(off.replace("Offset_","").replace(".txt",""))) for off in offsetFiles]
    print offsets
    # remove duplicate
    offsets = set(offsets)
    # produce couples of files
    for offset in offsets:
        if offset>0:
            mydriver.addOffsetFile('Offset_'+str(offset)+'.txt')
            mydriver.addOffsetFile('Offset_'+str(offset*-1)+'.txt')

mydriver=Driver("Driver_test.py","slitmask")
OffsetPairs()
mydriver.printObsfiles()
mydriver.printMaskAndBand()
mydriver.printFlat()
mydriver.printWavelengthFit()
mydriver.printBackground()
mydriver.printRectification()
mydriver.CloseFile()

**Comment by followthesheep** [comment]
There is a bug for me when I try to run the autodriver. It seems to be trying to read in a file called Offset_1.25_.txt when the actual file is named Offset_1.25.txt, without the extra underscore.

```
{'slitmask': [-1.25, 0.0, 1.25]}
slitmask
slitmask mode
Generating automatic driver file Driver_test.py
2015-06-30 11:35:27,823 -           IO.list_file_to_strings - INFO: Loading: Offset_1.25_.txt
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
/u/tdo/python/mosfire/apps/AutoDriver.py in <module>()
    348     mydriver.printObsfiles(obsLines)
    349     mydriver.addOffsetFiles(obsFiles)
--> 350     mydriver.printMaskAndBand()
    351     mydriver.printFlat()
    352     mydriver.printWavelengthFit()

/u/tdo/python/mosfire/apps/AutoDriver.py in printMaskAndBand(self)
     50     def printMaskAndBand(self):
     51         offsetfile = self.offsetFiles[0]
---> 52         fname = IO.list_file_to_strings(offsetfile)
     53 
     54         if os.path.isabs(fname[0]): path = fname[0]

/Network/Servers/galaxy1.astro.ucla.edu/volume1/GhezGroup/home-directories/tdo/python/mosfire/MOSFIRE/IO.pyc in list_file_to_strings(fname)
    340     for fname in filelist:
    341         info( "Loading: %s" % fname)
--> 342         inputs = np.loadtxt(fname, dtype= [("f", "S100")])
    343         path = ""
    344         start_index = 0

/group/ureka/Ureka/variants/common/lib/python2.7/site-packages/numpy/lib/npyio.pyc in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin)
    736                 fh = iter(bz2.BZ2File(fname))
    737             elif sys.version_info[0] == 2:
--> 738                 fh = iter(open(fname, 'U'))
    739             else:
    740                 fh = iter(open(fname))

IOError: [Errno 2] No such file or directory: 'Offset_1.25_.txt'
```

**Comment by lucarizzi** [comment]
Fixed

please use git pull to get the new AutoDriver.py file and try again.

Luca

**Comment by followthesheep** [comment]
The AutoDriver now makes the driver file. However, I think it is missing the variable obsfiles in the driver...

**Comment by MosfireDRP** [comment]
Fixed
a little to rushed in my early bug fix, sorry.

Try git pull again

Luca

**Comment by followthesheep** [comment]
I think there's a typo in the line in generated by the autodriver for the variable `LROIs`:

```
Wavelength.apply_lambda_sky_and_arc(maskname, band, obsfiles,  'Ne.txt', LROI, waveops)
```

should be:
```
Wavelength.apply_lambda_sky_and_arc(maskname, band, obsfiles,  'Ne.txt', LROIs, waveops)
```

**Comment by MosfireDRP** [comment]
@followthesheep I can't reproduce your error. 
In fact the lines of AutoDriver.py that produce that specific entry in the driver file are like this:


if self.useArgon and self.useNeon:
                self.addLine("Wavelength.apply_lambda_sky_and_arc(maskname, band, obsfiles,  'Ne.txt', LROIs, waveops)")
            if self.useArgon and not self.useNeon:
                self.addLine("Wavelength.apply_lambda_sky_and_arc(maskname, band, obsfiles,  'Ar.txt', LROIs, waveops)")
            if self.useNeon and not self.useArgon:
                self.addLine("Wavelength.apply_lambda_sky_and_arc(maskname, band, obsfiles,  'Ne.txt', LROIs, waveops)")


And as you can see the produce the variable LROIs and not LROI.

Could you separately email me the automatically generated driver file you that you get?

**Comment by followthesheep** [comment]
You're right, when I regenerated the file, it had the right variable. I'm not sure what happened, I probably changed it without realizing it sometime during my tests.

**Comment by lucarizzi** [comment]
Done
