### ISSUE TITLE
Plots in interactive wavelength fitting not displaying points for residuals

### ISSUE THREAD

**Issue by followthesheep** [Keck-DataReductionPipelines/MosfireDRP#28]
The interactive wavelength fitting right now looks like this:

![figure_1](https://cloud.githubusercontent.com/assets/3268415/8554340/373b584a-249e-11e5-8e60-d2f45c47f32d.png)

The bottom plot has no points on it. I think it's because the `xlim` variable in Wavelength.py is undefined. The plotting is done in `draw_found_lines()`.

**Comment by lucarizzi** [comment]
Is this true even after you use the "x" key to zoom with the cursor somewhere within the boundaries of the lower plot?
If so, this behavior was already there in the previous version

**Comment by followthesheep** [comment]
The points appear after I use the x key.

**Comment by MosfireDRP** [comment]
This error was there in the original version of the pipeline. 
Fixed today with eea36d6ad6b01520db56abb9eab547865ae365db
(for @followthesheep: I cherry-picked this commit to your install-update branch)
