### ISSUE TITLE
long2pos reduction for data taken before June 10 2015

### ISSUE THREAD

**Issue by jingwenwu2007** [Keck-DataReductionPipelines/MosfireDRP#33]
I have standard stars data taken before June 10, 2015. The new DRP provide drivers (Long2pos_K_driver.py and Long2pos.py) for the reduction, which is very nice! 
But I found my handled data only have two positions (offset_7.txt and offset_-7.txt), while the DRP drivers need positions at +-7 and at +-21.  Why I don't have offset at +-21, and does it matter?

**Comment by MosfireDRP** [comment]
Hi

If you used the long2pos script you must have either four or six positions, depending on whether you used the specphot option or not. In the assumption that you didn't do that, you should still have four pointings. 

Did you run the new mospy handle on your data or did you generate the offset files with the precious version of the pipeline ?

**Comment by jingwenwu2007** [comment]
yes, I generatee the offset files with the previous version of the pipeline. I will try to mospy handle with the new pipeline.

**Comment by jingwenwu2007** [comment]
Yes, I generated the offset files with a previous version, I will try to mospy handle the data with new pipeline. Thanks.

**Comment by MosfireDRP** [comment]
Very good
Once you do that you might also want to try the new automatic generation of the driver files 
Mospy autodriver

**Comment by jingwenwu2007** [comment]
The new version of handle successfully generated 4 offset positions for my long2pos data taken on jun 8, 2015, and the script works fine. Thanks! However, when I used it for the even oder long2pos data taken in May 2014, I still only find 2 offset positions: no PosA and PosC.

**Comment by MosfireDRP** [comment]
I'd be happy to try to figure this out. 
Can you tell me exactly which night and target you are trying to reduce ?

Thank you 
Luca

**Comment by jingwenwu2007** [comment]
My data was taken on UT May06, 2014, and the star for calibration is HIP55627. Thanks!

**Comment by lucarizzi** [comment]
I found the problem

For some reason that I do not know, one of the header keyword is set incorrectly.

To determine the sequence of observations, mospy handle relies on two keywords, XOFFSET and YOFFSET.

XOFFSET is -45 for position A, and +45 for position C.
YOFFSET goes to -7 and +7 on each position, for the A and B beams.

YOFFSET is correct in your observations, but XOFFSET is not: it is set to 0, both for position A and for position C.
Once you manually modify the keyword, it works.
I am an iraf person, so I did it with iraf:

ecl> hedit m140506_0261.fits[0] XOFFSET -45 update+ show+
ecl> hedit m140506_0262.fits[0] XOFFSET -45 update+ show+
ecl> hedit m140506_0263.fits[0] XOFFSET 45 update+ show+
ecl> hedit m140506_0264.fits[0] XOFFSET 45 update+ show+

Once you do this and you run again mospy handle, it creates all the necessary offset files and
mospy AutoDriver creates the driver file you need.

Note that you do not seem to have flats for this configuration.
Without flats, you cannot proceed, but you can use flats from another night.

**Comment by jingwenwu2007** [comment]
Dear Luca,

Thanks so much for checking the data for us.
As you pointed out, we don't have flats for this configuration on that run,
and that was a half-night run, so we don't have other flats in that
configuration. We switched the standard star mode from longslit to long2pos
under the suggestion by supporting astronomer, but I didn't realize I
should make up a flat for it in that configuration. Now the only other
flats I have for this configuration are the ones taken a year later, I
doubt whether those can be used for these data. So I wonder if you can help
 us to find any closer dates flats in the long2pos configuration that we
can borrow? We will highly appreciate it.

Best,
Jingwen

**Comment by lucarizzi** [comment]
Jingwen

I believe I have put everything you need on our ftpsite.

ftp ftp.keck.hawaii.edu <http://ftp.keck.hawaii.edu/>
anonymous

cd outgoing/lrizzi

With these files, you don’t need to run the Flat part of the driver file.

Luca

**Comment by jingwenwu2007** [comment]
Dear Luca,

Thanks so much for your help!
I have downloaded those files, and the iraf change of the offsets works fine in the new version of handle. I had also update those offset for K bands according to what you suggested for H band:
ecl> hedit m140506_0254.fits[0] XOFFSET -45 update+ show+
ecl> hedit m140506_0255.fits[0] XOFFSET -45 update+ show+
ecl> hedit m140506_0256.fits[0] XOFFSET 45 update+ show+
ecl> hedit m140506_0257.fits[0] XOFFSET 45 update+ show+

However, after putting those downloaded files into the directory, and run long2pos.py, I still get problem with error messages as follow:

……
2015-10-14 01:10:41,013 -           IO.fix_long2pos_headers - INFO: File /Users/jingwen/Jingwen/rawdata/Keck_MOSFIRE/2014May/m140506_0264.fits does not need to be updated
2015-10-14 01:10:41,152 -           IO.fix_long2pos_headers - INFO: File /Users/jingwen/Jingwen/rawdata/Keck_MOSFIRE/2014May/m140506_0261.fits does not need to be updated
2015-10-14 01:10:41,501 -           IO.list_file_to_strings - INFO: Loading: Ar.txt
loadtxt: Empty input file: "Ar.txt"
2015-10-14 01:10:41,502 -   Wavelength.           imcombine - INFO: combining Wavelength files
2015-10-14 01:10:41,502 -   Wavelength.           imcombine - INFO: list complete
Traceback (most recent call last):
  File "./Long2pos.py", line 42, in <module>
    Wavelength.imcombine(argon, maskname, band, waveops)
  File "/Users/jingwen/Jingwen/WISE/Mosfire2015A/MOSFIRE/Wavelength.py", line 233, in imcombine
    header.update("frameid", "median")
AttributeError: 'NoneType' object has no attribute 'update'

Then I found both the Ar.txt and Ne.txt are empty. It seems because we don't have lamps for this configuration, too. If this is the case, will there be any solution for it?

Sorry for these issues. We do appreciate your help!

Jingwen

**Comment by MosfireDRP** [comment]
Dear Jingwen

have you tried using the automatic driver generation (mospy AutoDriver) ?

If you do that, you will notice that when the Ne and Ar files are empty, even in the case of K observations, the pipeline defaults to using sky lines only.
While this is not the recommended options for short K observations, there are good chances that it might work, and it’s worth trying.

I did that, and I was in fact able to fully reduce your observations using sky lines only.

For your convenience, I have put a copy of the reduced that in our ftp server (look for a file called issue33.tar.gz in the same directory).

There are a few issue you should be aware of:

1. Not only the XOFFSET keyword was wrong, but the FRAMEID keyword was wrong too. For all your frames, the frameID was set to “B”. The “A” frames were mislabeled.
I used the same hedit iraf command to modify the FRAMEID keyword for 262, 264, 255 and 257 from B to A.

2. your posC files in K band are empty. It appears that the offset were not applied correctly. There are no stars in frames 256 and 257. The pipeline doesn’t have a problem with that so the reduced files are there, but they are empty. Not much we can do about it. PosA frames are ok and the standard star is there.


Please note that the final reduced frames are called
HIP55626_POS?_NARROW_?_eps.fits
the first ? can be either A or C
the second ? is either K or H

Luca

**Comment by jingwenwu2007** [comment]
Dear Luca,

It is so nice of you taking time doing these!
I have downloaded the data and they are perfect.
We do appreciate your help!

Jingwen

**Comment by lucarizzi** [comment]
My pleasure. Good luck with the paper !
