### ISSUE TITLE
Inconsistant header keywords in long2pos observations

### ISSUE THREAD

**Issue by jjencson** [Keck-DataReductionPipelines/MosfireDRP#36]
I am trying to reduce observations of telluric standards taken with the long2pos mask. In a given night, I have noticed some differences in the header keywords 'FRAMEID' and 'YOFFSET' between sets of observations of different stars that affect the running of the pipeline. For a set of 4 frames with the long2pos mask of a given star, sometimes the keyword values are
FRAMEID YOFFSET
object         21
object         7
object         -7
object        -21

and sometimes they are
FRAMEID YOFFSET
B                21
B                7
B                -7
B                -21

For the stars where the FRAMEID is 'object', the pipeline runs without any issues, and the header values are changed to the following at some point in the process:
FRAMEID YOFFSET
B                -7
A                7
B                -7
A                7

For the stars where the FRAMEID is 'B' for each of the 4 frames, the pipeline fails at the Background.handle_background step with the following exception:
Exception: Could not get observing plan from positions set(['B']). You must use the plan keyword

It is an easy fix for me to just change the header keywords to the ones that work with the pipeline, but I wanted to report the inconsistencies in the headers anyways. 

Thanks,
Jake

**Comment by lucarizzi** [comment]
Hi Jake
Thank you for the report. 
We are aware of the fact that at different times in the past the scripts used to take data have generated wrong headers. 
The solution is exactly the one you adopted: fix the header. 

For some of these cases, the pipeline takes care of the fixes as you noticed. For some other cases there is just too much variability for us to produce a consistent fix. 

Cheers
Luca
