### ISSUE TITLE
Background modelling issue

### ISSUE THREAD

**Issue by themiyan** [Keck-DataReductionPipelines/MosfireDRP#38]
We seem to have a problem with background modelling in some of our slits. This looks somewhat similar to an issue raised earlier (https://github.com/Keck-DataReductionPipelines/MosfireDRP/issues/30) but it is unlikely that it is caused by a star close to the slit-edge. 

The problem as you may see in the attached image, is that the background modelling of one of the slits in the H band is problematic. 
![screenshot 2016-01-08 06 15 09](https://cloud.githubusercontent.com/assets/5274688/12203873/4d6a7a7e-b5d5-11e5-8ebb-78f8de457478.png)

The combined flat image works well to compute the slit edges. But when the code comes to the background subtraction part it fails  to model the background of this slit accurately. 

On the lower left panel you can see the background model and for this specific slit it is roughly constant. I’m not sure why this happens. Perhaps this is an issue from the sigma clipping algorithm?
Due to this reason, the background subtraction of this slit is not performed correctly which leads to the following final image:
![screenshot 2016-01-08 06 21 42](https://cloud.githubusercontent.com/assets/5274688/12203930/892063bc-b5d5-11e5-994b-1963166e2032.png)

The full data products are here: https://www.dropbox.com/sh/rwidj4jcyb7cpce/AAAGvTsPXHt9fLDRYrayzD16a?dl=0

Thanks,

Themiya.

**Comment by MosfireDRP** [comment]
I am downloading the data and attempting a reduction to reproduce the problem and investigate.

luca

**Comment by MosfireDRP** [comment]
The problem is confirmed and I can also confirm that it happens at the level of creating the model for the background.
Here is an image from my own reduction

![image](https://cloud.githubusercontent.com/assets/9344283/12284479/e76e09f2-b953-11e5-90e5-15c5f90affce.png)

**Comment by themiyan** [comment]
Thanks Luca. Yes it seems a worry, I had a look over the weekend and cannot seem to find the cause for the problem. 
As you see it affects some of the masks but not all of them. Using flats from a different night or selecting a sub sample of exposures to reduce did not solve the problem. 

![screenshot 2016-01-12 23 42 35](https://cloud.githubusercontent.com/assets/5274688/12290529/63fbdb02-b986-11e5-8385-941c9a51159f.png)

A manual A-B of the stacks looks similar to the DRP output as well. The problem may lie on the Bspline fitting procedure done in the background modelling step?
As you see compared to the neighbouring slit the fit of the background doesn't accurately model the sky lines etc. Perhaps it fails to estimate the transmission function?

![screenshot 2016-01-12 18 51 24](https://cloud.githubusercontent.com/assets/5274688/12290734/75089a4c-b987-11e5-862c-91914afd7e2b.png)

**Comment by MosfireDRP** [comment]
Small progress. I modified the pipeline so that it runs in a python notebook. 
If I run the background modeling on slit 1, I get a nice background model

![image](https://cloud.githubusercontent.com/assets/9344283/12344132/026eb34c-bade-11e5-87c6-e39d750ca019.png)

If I run it on the troubled slit, which is number 2, I get the gradient that we don't want to see

![image](https://cloud.githubusercontent.com/assets/9344283/12344145/22969cc0-bade-11e5-8bd2-3a4fcd4afa19.png)

That's it for this week (got to prepare slides for SSC!). But I hope this will be a useful instrument to investigate where things go wrong.

**Comment by MosfireDRP** [comment]
![image](https://cloud.githubusercontent.com/assets/9344283/12364965/e629c01c-bb75-11e5-9f5c-19c5e1d04e02.png)

The problem was a masked array. The median was returned as "masked" instead of the value, which produced problems with the bspline calculation. Should work now.

**Comment by followthesheep** [comment]
Hi Luca,
What branch are you working on? Are you on master? It seems like master is
behind the 2015A release. What is our development model for the master
branch? Is it the latest stable? Or some sort of development branch?

Tuan
