### ISSUE TITLE
Warning showing too high temperature of the "channel A" compared to the desired temperature

### ISSUE THREAD

**Issue by kojitaka0409** [Keck-DataReductionPipelines/MosfireDRP#39]
I'm executing the DRP with our MOSFIRE data taken on 2016/01/04 (I'm a student of the PI on that day).
During the procedure, I encountered the WARNING, 
”WARNING: The temperature of the detector is 77.118 where it should be 77.000 deg. Please notify Keck support staff."
(I checked the scripts and this massage will appear when the temperature of "Channel A" differs by more than 0.1 deg from the desired temperature = 77.000 deg.)

It shows up many times when the pipeline reads "m160104_0334.fits" or "m160104_0335.fits" with 'readmosfits'.  The headers of these fits files show exactly the same value of temperature at "channel A" (REGTMP1 = 77.11799622).
Something seemed to happen during the observation corresponding to "m160104_0334.fits" and "m160104_0335.fits".

And my questions are;
How can I deal with this problem?
How much do you think this problem affects the reduced data?

I'm using MosfireDRP-2015A on OS X 10.10.4.
Here attached the transition of the temperatures (Y-axis) according to the ID (X-axis) during the night.

Takashi Kojima

![regtmp1](https://cloud.githubusercontent.com/assets/14871398/12420097/bd2b90b0-befd-11e5-9361-e112b2852f20.png)

**Comment by lucarizzi** [comment]
Mosfire experts: do you know the answer to this question ?

**Comment by csteidel** [comment]
I thought the temperature checking was removed- this dates back a long time to when Nick was being over-zealous
checking all sorts of things in each image header as part of the DRP. I think it should be deprecated, as it causes
a lot more trouble than it is worth— if the temps were really different enough to be significant, then you would know it
from other signs.  Here it’s just a temperature sensor or DCS communications glitch —

**Comment by lucarizzi** [comment]
Thank you Chuck 
I will remove the check from the pipeline

**Comment by kojitaka0409** [comment]
As Chuck said, I can't find out any other noticeable signs in these two fits files. 

Thank you Chuck and Luca for your help.

**Comment by lucarizzi** [comment]
Closed by e66f10e4
