### ISSUE TITLE
Making MosfireDRP compatible with Anaconda distribution

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/MosfireDRP#41]
I am trying to make the pipeline compatible with Anaconda. Not only some of our observers don't want to install Ureka, but Anaconda is rapidly becoming the standard for scientific computing. Besides, our other python pipeline hosted at Keck (NIRSPEC) uses Anaconda.

First steps so far:

Install pyfits - pip install pyfits

Install pyraf - pip install pyraf

Install PyObjC 

pip install pyobjc fails on my 10.10 Mac os X
Workaround:
env CC=clang pip install -U pyobjc-core
env CC=clang pip install -U pyobjc

Running the edge detection on a flat fails with this error:

Traceback (most recent call last):
  File "Driver.py", line 21, in <module>
    Flats.handle_flats('Flat.txt', maskname, band, flatops)
  File "/Users/lrizzi/MosfireDRP/MOSFIRE/Flats.py", line 145, in handle_flats
    results = find_and_fit_edges(data, header, bs, options,edgeThreshold=edgeThreshold)
  File "/Users/lrizzi/MosfireDRP/MOSFIRE/Flats.py", line 917, in find_and_fit_edges
    bs.scislit_to_csuslit(next)[0],
IndexError: list index out of range

While running the Ureka python does not generate the error on the same dataset. Investigating...

**Comment by lucarizzi** [comment]
Fixed a few issues with commit cba610218ba97492def64962a98bae791e268e7e on a new branch (Anaconda)

**Comment by lucarizzi** [comment]
Background subtraction is broken with Anaconda. I get a black image (all zero).
On the upside, the pipeline runs almost twice as fast with Anaconda than it does with Ureka for some reason. 
Full reduction of a mask with Ureka: 21 minutes
Same reduction with Anaconda: 11 minutes

**Comment by lucarizzi** [comment]
Found the problem with the background subtraction

Ureka uses numpy 1.9.1, Anaconda uses 1.10.1
They have a different behaviour when it comes to calculating the median of an array containing NaN.

1.9.1 (Ureka)
x = np.array([1,2,3,4,5,6,7,8,nan,nan,nan])
np.median(x) returns 6
np.nanmedian(x) returns 4.5 (this functions automatically excluded nan values)

1.10.1 (Anaconda)
x = np.array([1,2,3,4,5,6,7,8,nan,nan,nan])
np.median(x) returns nan and a warning
np.nanmedian(x) returns 4.5

SO which one do we like more?

This happens in line 917 of Background.py
model[oob] = np.median(ss)

I have attempted to replace this line with
model[oob] = np.median(ss[~np.isnan(ss)])
which automatically gets rid of the NaN, and now Background.py works fine with Anaconda and with Ureka.
It also produces the same results, as far as I can see.

See 01ce98b

**Comment by followthesheep** [comment]
I think np.nanmedian should be used. I don't think we should count the
nan's in computing the median. I think we should be explicit by changing
all the medians to nanmedian(). We should also check other functions for
incompatibility with nan's, such as median, min, and max...

Tuan

**Comment by MosfireDRP** [comment]
I agree but it seems that nanmedian was introduced recently. I am afraid that some people might be using old numpy version that don’t have nanmedian.
Or maybe this is not a concern?

**Comment by nickkonidaris** [comment]
Hi All:

In this case for spline construction, the nanmedian is correct. I don't
have my notes, but I think there were some cases where I wanted the nans to
participate in the measurement. For instance, if the nan represents an
upper limit, then it does affect the median. On the other hand, I can't
remember if my statement makes is about the MOSFIRE pipeline or the SEDM
pipeline.

If you want to gracefully handle different distributions, then you have to
do things like:

try:
  import numpy.nanmedian
except:
  def nanmedian(x): ...

You may find this to be cumbersome, but it should work.

OR

I've recently been using vagrant for development work and it may solve the
problem you're facing with MOSDRP. On the other hand, it makes the install
file huge.

~ N




On Tue, Feb 2, 2016 at 5:18 PM, MosfireDRP <notifications@github.com> wrote:

> I agree but it seems that nanmedian was introduced recently. I am afraid
> that some people might be using old numpy version that don’t have nanmedian.
> Or maybe this is not a concern?
>
>
>
> > On Feb 2, 2016, at 3:16 PM, Tuan Do <notifications@github.com> wrote:
> >
> > I think np.nanmedian should be used. I don't think we should count the
> > nan's in computing the median. I think we should be explicit by changing
> > all the medians to nanmedian(). We should also check other functions for
> > incompatibility with nan's, such as median, min, and max...
> >
> > Tuan
> >
> > On Tue, Feb 2, 2016 at 5:05 PM, lucarizzi <notifications@github.com>
> wrote:
> >
> > > Found the problem with the background subtraction
> > >
> > > Ureka uses numpy 1.9.1, Anaconda uses 1.10.1
> > > They have a different behaviour when it comes to calculating the
> median of
> > > an array containing NaN.
> > >
> > > 1.9.1 (Ureka)
> > > x = np.array([1,2,3,4,5,6,7,8,nan,nan,nan])
> > > np.median(x) returns 6
> > > np.nanmedian(x) returns 4.5 (this functions automatically excluded nan
> > > values)
> > >
> > > 1.10.1 (Anaconda)
> > > x = np.array([1,2,3,4,5,6,7,8,nan,nan,nan])
> > > np.median(x) returns nan and a warning
> > > np.nanmedian(x) returns 4.5
> > >
> > > SO which one do we like more?
> > >
> > > This happens in line 917 of Background.py
> > > model[oob] = np.median(ss)
> > >
> > > I have attempted to replace this line with
> > > model[oob] = np.median(ss[~np.isnan(ss)])
> > > which automatically gets rid of the NaN, and now Background.py works
> fine
> > > with Anaconda and with Ureka.
> > > It also produces the same results, as far as I can see.
> > >
> > > See 01ce98b
> > > <
> https://github.com/Keck-DataReductionPipelines/MosfireDRP/commit/01ce98b23c5d69d61c41c9678178ba71cc7716bb
> >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/Keck-DataReductionPipelines/MosfireDRP/issues/41#issuecomment-178931709
> >
> > > .
> > >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/Keck-DataReductionPipelines/MosfireDRP/issues/41#issuecomment-178937145
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Keck-DataReductionPipelines/MosfireDRP/issues/41#issuecomment-178939542>
> .
>



-- 
+1 831 704 6425

**Comment by MosfireDRP** [comment]
Thanks Nick

I might be painful but I will try to look at each case in which we use median and figure out if we want to count the NaN or not, and maybe ask you if I am in doubt.

Also, good suggestion on the try/except for the import of nanmedian. I think that is a good idea

Luca

**Comment by lucarizzi** [comment]
6aced0a

Shui correctly pointed out that pyfits is already part of Anaconda, so no need to install it.

**Comment by followthesheep** [comment]
Can we use the fits module in astropy? I don't think pyfits is getting
updated anymore. If we are going to use anaconda, we might as well also use
astropy. It has potentially lots of relevant modules that we might want to
use for MOSFIRE.

Tuan

**Comment by lucarizzi** [comment]
Yes indeed

Ureka contains astropy as well

I will make the changes
Luca

**Comment by joshwalawender** [comment]
I'm closing this for now in order to push us toward release.  The current code is using @lucarizzi 's solution rather than `nanmedian`.  I'm leaving it that way under the philosophy of "if it ain't broke ...".  PR's welcome if you feel strongly it should be different.

**Comment by followthesheep** [comment]
Could you clarify what you mean? Does this mean that the pipeline is not
compatible with conda?

**Comment by joshwalawender** [comment]
@followthesheep Sorry, I guess that wasn't clear.  The next release of the pipeline is definitely compatible with conda, in fact that is the baseline assumption for the install (see the new manual described in PR #57 ).

The only controversy is that I have left in the handling of `nan`s which looks like:

```
model[oob] = np.median(ss[~np.isnan(ss)])
```

rather than something like

```
model[oob] = nanmedian(ss)
```

If we use the second case, there would need to be some sort of try/except in case the numpy version was too old to include `nanmedian` as was discussed above.
