### ISSUE TITLE
Removing redundant WCS header info

### ISSUE THREAD

**Issue by themiyan** [Keck-DataReductionPipelines/MosfireDRP#44]
Will it be possible to remove CDELTi from the headers in future?
The reason being CD1_1 is similar in meaning for CRDELT1  but the values are different in the headers. 

So when viewing data with the newest ds9 this creates a bug in the wavelength solution (see attached image by Ivo Labbe). 
It seems ds9 used to give priority to CD1 over CRDELT1 but it is not the case anymore. Ivo has submitted a bug report to ds9 and they will allow this to be the default now.
So this should be fixed in next releases of ds9, but it might be good to remove redundant WCS headers from the outputs anyways to avoid confusion?

CDELT1  =                    1  
CDELT2  =                    1  
CNAME1  = 'angstrom'  
CNAME2  = 'pixel   '  
CD1_1   =    1.628959276018577 / Angstrom/pixel  
CD1_2   =                    0  
CD2_1   =                    0  
CD2_2   =                    1 

<img width="503" alt="v7 4 1" src="https://cloud.githubusercontent.com/assets/5274688/12995342/c734f6b6-d17a-11e5-8750-271dfa5a277a.png">
<img width="480" alt="v6 1 2" src="https://cloud.githubusercontent.com/assets/5274688/12995345/cac6a446-d17a-11e5-80ac-cadda25b2810.png">

**Comment by dmkassis** [comment]
I will add this to our mosfire punch list.

**Comment by joshwalawender** [comment]
This is fixed in the soon to be released 2016 version of the DRP.  The fix we implemented was to force CDELT and CD to be equal, this seemed to satisfy ds9, IRAF's splot, and `astropy.wcs`.
