### ISSUE TITLE
Matplotlib backend broken on linux

### ISSUE THREAD

**Issue by lucarizzi** [Keck-DataReductionPipelines/MosfireDRP#53]
I just tried to run the pipeline with Anaconda and the Qt4Agg back end and it produced BadDraw errors. Only a grey window shows up. It seems to be a well known issue with matplotlib.

PySide is also not working.

I got the pipeline (and actually any basic plot) to work by using TkAgg. I also tested WXAgg and it works after installing wxpython.

**Comment by joshwalawender** [comment]
Closing as the 2016 release solved this by forcing the use of `TkAgg` in the driver file.  This is definitely an inelegant fix, but until the issues with backends (including the macOS issue discussed in #67) are solved, this seems the path of least resistance.
