### ISSUE TITLE
Pipeline will crash in interactive mode if user quits before fitting all slits

### ISSUE THREAD

**Issue by joshwalawender** [Keck-DataReductionPipelines/MosfireDRP#55]
We should have warning before quitting or prevent quitting the interactive plot (in Wavelength.fit_lambda_interactively) or have some better messaging because the crash traceback is difficult for a user to understand.

I think a more intuitive response would be that when a user quits the interactive plot, the system should fit any remaining slits with default settings.  I would guess that this ends up being identical to running with the bypassflag=True.

**Comment by joshwalawender** [comment]
Addressed in PR #75 by improving log messages to indicate to use why the failure occurred.

**Comment by anstockton** [comment]
Hi Josh,

I keep trying to unsubscribe, since I no longer use MOSFIRE, but it doesn’t seem to take. Is there any way to get me off the list?

Thanks.  

Alan Stockton
Institute for Astronomy
University of Hawaii

**Comment by joshwalawender** [comment]
@anstockton You should be able to control notifications from your GitHub account settings.  Anything you're getting is going through GitHub.
