### ISSUE TITLE
The .original files generated by fix_long2pos_headers are counted again by handle

### ISSUE THREAD

**Issue by joshwalawender** [Keck-DataReductionPipelines/MosfireDRP#62]
It looks like the duplicate .original files generated by fix_long2pos_headers get counted on subsequent `mospy handle` runs leading to a single raw file being listed twice in the output list files (once as `.fits` and once as `.fits.original`).

**Comment by lucarizzi** [comment]
Oops. Not good ! 

I usually do mospy handle *.fits so maybe that is why I never saw this behavior

**Comment by joshwalawender** [comment]
Addressed by #103
