### ISSUE TITLE
Improvements to the installation/instruction manual

### ISSUE THREAD

**Issue by MosfireDRP** [Keck-DataReductionPipelines/MosfireDRP#7]
The DRP manual (docx file) says filename_sig.fits is a variance but it should be sigma, standard deviation.

**Comment by MosfireDRP** [comment]
The current version claims that Ureka 1.0 is required, but 1.4.1 now works

**Comment by MosfireDRP** [comment]
the installation instructions only explain how to work with .cshrc, and if the user does not have .cshrc, it points to a .cshrc file for download which contains a call to source /usr/stsci....
That call is not necessary and in fact it generates confusion

We should add information on how to use a .bashrc as well as a .cshrc

**Comment by followthesheep** [comment]
Maybe we can put the manual into git as well? That way we can edit and
track it more easily.

Tuan

**Comment by MosfireDRP** [comment]
HI Tuan

The manual is into git.
It is in a different branch called gh-pages


That is the branch that generates the web pages so I think it’s the right place for it.

Feel free to clone that branch too.

If we feel it would be better to have it also on the main branch, and only occasionally copy over the new version to gh-pages, that is good too.

Luca

**Comment by lucarizzi** [comment]
@followthesheep suggests adding a section specifying clearly which output files are generated, especially in the case of long2pos and longslit, which at present time might be confusing.

**Comment by joshwalawender** [comment]
How would everyone feel about migrating the manual from a docx file to a set of markdown pages as part of the github pages web site?  I've used [jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/) with github pages before and it seems to work reasonably well.  I could make a new gh-pages branch and copy the manual contents in to a set of markdown documents which would be easier to edit and track changes.

**Comment by followthesheep** [comment]
That sounds good to me! We should make sure it can still get printed as one document though for those who want the whole thing.

**Comment by joshwalawender** [comment]
Good point about having it available as a single file.  I had started this already and had begun splitting things out in to multiple .md files for easier editing.  

It looks like we can build a single pdf from multiple .md files using pandoc, but this would be a manual step which we would have to execute after each change to the .md file contents.

**Comment by joshwalawender** [comment]
I did a quick install of jekyll plus a copy and paste of the docx file contents in to .md files.  The results are in the gh-pages-no_docx branch.  The pdf built from the md files is there (in the _manual) directory or linked from the front page.

I did no real editing of the manual, but I did come across a few minor typos which I fixed.  I also noticed that there are a couple of missing equations in the docx file, so I put notes in the md files where those should go and we should figure out what the content should be there.

**Comment by joshwalawender** [comment]
Ok, I've got a jekyll + markdown version of the manual working on my fork of the DRP repository (the URL is my personal web page which is served by github.io), see here: http://www.twilightlandscapes.com/MosfireDRP/

If this looks reasonable, then I can form a pull request to replace the current manual (the original docx file is still available in the repo).

**Comment by lucarizzi** [comment]
Looks good !
