### ISSUE TITLE
Transition DRP Manual to Wiki?

### ISSUE THREAD

**Issue by joshwalawender** [Keck-DataReductionPipelines/MosfireDRP#81]
Hi all,

Would it be a good idea to move the web based manual ([http://keck-datareductionpipelines.github.io/MosfireDRP/](http://keck-datareductionpipelines.github.io/MosfireDRP/)) to the Wiki for this project here on GitHub?  The advantage would be that the manual is more fluid and is more easily user updatable as things change.  I don't know if that is something we want or not.

I can tackle this if we think it is a better strategy than using GitHub Pages as we are now.  I'm looking for input as I think we should probably have just one manual to avoid confusion, so if we move that content to the wiki, I'd remove the web site version entirely.

-Josh

**Comment by MosfireDRP** [comment]
Yes sounds good.

**Comment by followthesheep** [comment]
This sounds like a good idea, but I have a question. Is there a way to
render into pdf or some offline form? I think people would like that as a
reference and I find it convenient not to have to go online when checking
something quickly.

**Comment by joshwalawender** [comment]
Good question.  I don't think so (at least not easily with good formatting).  That is a big advantage of the web page which can be rendered straight to PDF.
