### ISSUE TITLE
Driver.py Failing at Wavelength Fitting for the Entire Slit

### ISSUE THREAD

**Issue by askoch785** [Keck-DataReductionPipelines/MosfireDRP#82]
Hello,

I am trying to reduce a data set and the Driver.py file at the "Wavelength Fitting for the Entire Slit." I am receiving the following message:

Traceback (most recent call last):
  File "Driver.py", line 36, in <module>
    Wavelength.fit_lambda(maskname, band, obsfiles, obsfiles,waveops)
  File "/media/alex/easystore/anaconda2/envs/mosfire_drp/lib/python2.7/site-packages/MOSFIRE-1.0.dev0-py2.7.egg/MOSFIRE/Wavelength.py", line 309, in fit_lambda
    guessnames = IO.list_file_to_strings(wavenames)
  File "/media/alex/easystore/anaconda2/envs/mosfire_drp/lib/python2.7/site-packages/MOSFIRE-1.0.dev0-py2.7.egg/MOSFIRE/IO.py", line 346, in list_file_to_strings
    inputs = np.loadtxt(fname, dtype= [("f", "S100")])
  File "/media/alex/easystore/anaconda2/envs/mosfire_drp/lib/python2.7/site-packages/numpy/lib/npyio.py", line 927, in loadtxt
    % line_num)
ValueError: Wrong number of columns at line 2

Thank you!

**Comment by lucarizzi** [comment]
What night are you trying to reduce?
Which object/filter?
Can we see the driver file and all the file lists that are in your current directory (Dark, Flat, ...) ?

Looks a lot like the DRP is trying to load a list of files and it finds it empty.

**Comment by askoch785** [comment]
We are trying to reduce the MOSFIRE Mask7 data from 20170930 in the H band. I have attached the Driver file (saved as a .txt file for attachment):

[Driver.txt](https://github.com/Keck-DataReductionPipelines/MosfireDRP/files/1446914/Driver.txt)


The Handle step created the following files:

Aborted.txt
Ar.txt
Flat.txt
mosfire_drp.log
Ne.txt
Offset_1.2.txt
Offset_1.5.txt
Offset_-1.2.txt
Offset_-1.5.txt

After running the DRP up to the error, the following files were also created:

barset.npy
combflat_2d_H.fits
lambda_center_coeffs_wave_stack_H_m170930_0011.fits.gz-0052.fits.gz.npy
pixelflat_2d_H.fits
slit-edges_H.npy
slit-edges_H.reg
wave_stack_H_m170930_0011.fits.gz-0052.fits.gz.npy


I hope this helps. Please let me know if I can provide any more info.

Thank you!

**Comment by lucarizzi** [comment]
I think that your problem is the use of .gz files. Can you try to gunzip all your files and re-run mospy AutoDriver?

The line:
Wavelength_file = 'lambda_solution_wave_stack_H_m170930_0011.fits.gz-0052.fits.gz.fits'

Should read:
Wavelength_file = 'lambda_solution_wave_stack_H_m170930_0011-0052.fits'

Luca

**Comment by joshwalawender** [comment]
Note this is the same as #58 we should try to address this.

**Comment by lucarizzi** [comment]
I was thinking the same 

At the very least stop the auto driver generation if it encounters gzipped files and ask the user to take action. 

We could, of course, gunzip but I wonder if it would be a bit invasive.
